services:
  # Web service - Flask application with SocketIO
  - type: web
    name: hotelchat-web
    runtime: python
    region: oregon
    plan: standard
    previews:
      enabled: true
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn chat_server:app --config gunicorn.conf.py"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: LOG_LEVEL
        value: INFO
      - key: WEB_CONCURRENCY
        value: 4
      - key: OPENAI_CONCURRENCY
        value: 5
      - key: DATABASE_URL
        fromDatabase:
          name: hotelchat-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: hotelchat-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false

  # Celery worker
  - type: worker
    name: hotelchat-worker
    runtime: python
    region: oregon
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_app.worker worker -l INFO -Q default,whatsapp --concurrency=3"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        fromDatabase:
          name: hotelchat-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: hotelchat-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false

  - type: redis
    name: hotelchat-redis
    region: oregon
    plan: standard
    ipAllowList: [] # Render services in the same account can connect automatically

databases:
  - name: hotelchat-db
    region: oregon
    plan: standard